#!/usr/bin/env python3
"""
HDF5 IK Solutions Inspector

This script provides utilities to inspect and analyze IK solutions HDF5 files
generated by run_app_v2.py.

Usage:
    python inspect_ik_solutions.py --h5_file <path_to_h5_file> [options]

Examples:
    # Show basic structure
    python inspect_ik_solutions.py --h5_file data/output/100/ik_solutions_all_20250102_143022.h5

    # Show detailed statistics
    python inspect_ik_solutions.py data/output/100/ik_solutions_all_20250102_143022.h5 --detailed

    # Show specific viewpoint
    python inspect_ik_solutions.py data/output/100/ik_solutions_all_20250102_143022.h5 --viewpoint 0
"""

import argparse
import json
import os
import sys
from typing import Dict, List, Any

import h5py
import numpy as np


def print_separator(char='=', length=60):
    """Print a separator line."""
    print(char * length)


def print_metadata(h5_file: h5py.File) -> Dict[str, Any]:
    """
    Print metadata from HDF5 file.

    Args:
        h5_file: Open HDF5 file handle

    Returns:
        Dictionary of metadata
    """
    print_separator()
    print("METADATA")
    print_separator()

    metadata_grp = h5_file['metadata']
    metadata = {}

    for key in metadata_grp.attrs.keys():
        value = metadata_grp.attrs[key]
        metadata[key] = value
        print(f"  {key}: {value}")

    print()
    return metadata


def print_file_structure(h5_file: h5py.File, max_viewpoints: int = 5):
    """
    Print hierarchical structure of HDF5 file.

    Args:
        h5_file: Open HDF5 file handle
        max_viewpoints: Maximum number of viewpoints to show in detail
    """
    print_separator()
    print("FILE STRUCTURE")
    print_separator()

    # Count viewpoint groups
    viewpoint_groups = [key for key in h5_file.keys() if key.startswith('viewpoint_')]
    num_viewpoints = len(viewpoint_groups)

    print(f"Total groups: {len(h5_file.keys())}")
    print(f"  - metadata (1)")
    print(f"  - viewpoint_XXXX ({num_viewpoints})")
    print()

    # Show metadata structure
    print("metadata/")
    metadata_grp = h5_file['metadata']
    for key in metadata_grp.attrs.keys():
        print(f"  ├── {key} (attribute)")
    print()

    # Show sample viewpoint structure
    if viewpoint_groups:
        sample_vp = viewpoint_groups[0]
        print(f"{sample_vp}/ (sample viewpoint structure)")
        vp_grp = h5_file[sample_vp]

        # Show attributes
        for key in vp_grp.attrs.keys():
            value = vp_grp.attrs[key]
            print(f"  ├── {key}: {value} (attribute)")

        # Show datasets
        for key in vp_grp.keys():
            dataset = vp_grp[key]
            print(f"  ├── {key}: shape={dataset.shape}, dtype={dataset.dtype}")

    print()

    # List all viewpoints (limited)
    print(f"Viewpoint groups ({num_viewpoints} total):")
    for i, vp_name in enumerate(sorted(viewpoint_groups)[:max_viewpoints]):
        vp_grp = h5_file[vp_name]
        num_all = vp_grp.attrs['num_all_solutions']
        num_safe = vp_grp.attrs['num_safe_solutions']
        selected = vp_grp.attrs['selected_solution_index']
        print(f"  {vp_name}: {num_all} total, {num_safe} safe, selected={selected}")

    if num_viewpoints > max_viewpoints:
        print(f"  ... and {num_viewpoints - max_viewpoints} more")

    print()


def compute_statistics(h5_file: h5py.File) -> Dict[str, Any]:
    """
    Compute statistics from all viewpoints.

    Args:
        h5_file: Open HDF5 file handle

    Returns:
        Dictionary of statistics
    """
    viewpoint_groups = [key for key in h5_file.keys() if key.startswith('viewpoint_')]

    stats = {
        'total_viewpoints': len(viewpoint_groups),
        'num_all_solutions': [],
        'num_safe_solutions': [],
        'selected_indices': [],
        'collision_free_rates': [],
    }

    for vp_name in viewpoint_groups:
        vp_grp = h5_file[vp_name]
        num_all = vp_grp.attrs['num_all_solutions']
        num_safe = vp_grp.attrs['num_safe_solutions']
        selected = vp_grp.attrs['selected_solution_index']

        stats['num_all_solutions'].append(num_all)
        stats['num_safe_solutions'].append(num_safe)
        stats['selected_indices'].append(selected)

        if num_all > 0:
            collision_free_rate = num_safe / num_all
            stats['collision_free_rates'].append(collision_free_rate)
        else:
            stats['collision_free_rates'].append(0.0)

    return stats


def print_statistics(stats: Dict[str, Any]):
    """
    Print statistics summary.

    Args:
        stats: Statistics dictionary from compute_statistics()
    """
    print_separator()
    print("STATISTICS")
    print_separator()

    num_all = np.array(stats['num_all_solutions'])
    num_safe = np.array(stats['num_safe_solutions'])
    selected = np.array(stats['selected_indices'])
    cf_rates = np.array(stats['collision_free_rates'])

    print(f"Total viewpoints: {stats['total_viewpoints']}")
    print()

    print("All IK Solutions:")
    print(f"  Total: {num_all.sum()}")
    print(f"  Mean per viewpoint: {num_all.mean():.2f}")
    print(f"  Std dev: {num_all.std():.2f}")
    print(f"  Min: {num_all.min()}")
    print(f"  Max: {num_all.max()}")
    print()

    print("Safe IK Solutions (collision-free):")
    print(f"  Total: {num_safe.sum()}")
    print(f"  Mean per viewpoint: {num_safe.mean():.2f}")
    print(f"  Std dev: {num_safe.std():.2f}")
    print(f"  Min: {num_safe.min()}")
    print(f"  Max: {num_safe.max()}")
    print()

    print("Collision-Free Rate:")
    print(f"  Mean: {cf_rates.mean():.2%}")
    print(f"  Std dev: {cf_rates.std():.2%}")
    print(f"  Min: {cf_rates.min():.2%}")
    print(f"  Max: {cf_rates.max():.2%}")
    print()

    print("Selected Solutions:")
    num_selected = (selected >= 0).sum()
    print(f"  Viewpoints with selection: {num_selected}/{stats['total_viewpoints']}")
    print(f"  Viewpoints without selection: {stats['total_viewpoints'] - num_selected}")
    print()

    # Histogram of number of solutions
    print("Distribution of IK Solutions per Viewpoint:")
    bins = [0, 1, 2, 4, 8, 16, 32, 100]
    hist, _ = np.histogram(num_all, bins=bins)
    for i in range(len(bins) - 1):
        if i == len(bins) - 2:
            print(f"  {bins[i]}-{bins[i+1]}: {hist[i]} viewpoints")
        else:
            print(f"  {bins[i]}-{bins[i+1]-1}: {hist[i]} viewpoints")
    print()


def print_viewpoint_detail(h5_file: h5py.File, viewpoint_index: int):
    """
    Print detailed information about a specific viewpoint.

    Args:
        h5_file: Open HDF5 file handle
        viewpoint_index: Index of viewpoint to inspect
    """
    vp_name = f'viewpoint_{viewpoint_index:04d}'

    if vp_name not in h5_file:
        print(f"Error: {vp_name} not found in file")
        return

    print_separator()
    print(f"VIEWPOINT {viewpoint_index} DETAILS")
    print_separator()

    vp_grp = h5_file[vp_name]

    # Print attributes
    print("Attributes:")
    for key in vp_grp.attrs.keys():
        value = vp_grp.attrs[key]
        print(f"  {key}: {value}")
    print()

    # Print world pose
    if 'world_pose' in vp_grp:
        world_pose = np.array(vp_grp['world_pose'])
        print("World Pose (4x4):")
        for row in world_pose:
            print(f"  [{row[0]:8.4f} {row[1]:8.4f} {row[2]:8.4f} {row[3]:8.4f}]")
        print(f"  Position: [{world_pose[0, 3]:.4f}, {world_pose[1, 3]:.4f}, {world_pose[2, 3]:.4f}]")
        print()

    # Print IK solutions summary
    if 'all_ik_solutions' in vp_grp:
        all_sols = np.array(vp_grp['all_ik_solutions'])
        collision_mask = np.array(vp_grp['collision_free_mask'])

        print(f"All IK Solutions ({len(all_sols)}):")
        for i, sol in enumerate(all_sols):
            is_safe = collision_mask[i]
            status = "✓ SAFE" if is_safe else "✗ COLLISION"
            selected = vp_grp.attrs['selected_solution_index']
            is_selected = (i == selected) and is_safe

            marker = " ← SELECTED" if is_selected else ""
            print(f"  [{i}] {status}{marker}")
            print(f"      joints: [{sol[0]:7.4f}, {sol[1]:7.4f}, {sol[2]:7.4f}, "
                  f"{sol[3]:7.4f}, {sol[4]:7.4f}, {sol[5]:7.4f}]")
        print()

    # Show safe solutions only
    safe_sols = all_sols[collision_mask]
    if len(safe_sols) > 0:
        print(f"Safe Solutions Only ({len(safe_sols)}):")
        safe_idx = 0
        for i, sol in enumerate(all_sols):
            if collision_mask[i]:
                selected = vp_grp.attrs['selected_solution_index']
                marker = " ← SELECTED" if safe_idx == selected else ""
                print(f"  [{safe_idx}]{marker} joints: [{sol[0]:7.4f}, {sol[1]:7.4f}, {sol[2]:7.4f}, "
                      f"{sol[3]:7.4f}, {sol[4]:7.4f}, {sol[5]:7.4f}]")
                safe_idx += 1
        print()

def main():
    parser = argparse.ArgumentParser(
        description='Inspect IK solutions HDF5 files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    parser.add_argument(
        '--h5_file',
        type=str,
        help='Path to HDF5 file to inspect'
    )
    parser.add_argument(
        '--detailed',
        action='store_true',
        help='Show detailed statistics'
    )
    parser.add_argument(
        '--viewpoint',
        type=int,
        metavar='INDEX',
        help='Show details for specific viewpoint index'
    )
    parser.add_argument(
        '--max-viewpoints',
        type=int,
        default=5,
        help='Maximum number of viewpoints to show in structure (default: 5)'
    )

    args = parser.parse_args()

    # Check if file exists
    if not os.path.exists(args.h5_file):
        print(f"Error: File not found: {args.h5_file}")
        sys.exit(1)

    # Open HDF5 file
    print(f"\nInspecting: {args.h5_file}")
    print(f"File size: {os.path.getsize(args.h5_file) / 1024:.2f} KB")
    print()

    with h5py.File(args.h5_file, 'r') as f:
        # Always show metadata and structure
        metadata = print_metadata(f)
        print_file_structure(f, max_viewpoints=args.max_viewpoints)

        # Show statistics if requested
        if args.detailed:
            stats = compute_statistics(f)
            print_statistics(stats)

        # Show specific viewpoint if requested
        if args.viewpoint is not None:
            print_viewpoint_detail(f, args.viewpoint)

    print_separator()
    print("Inspection complete!")
    print_separator()


if __name__ == "__main__":
    main()
